2025-04-28 12:13:19 [ERROR]: Error in approving leave: Cannot read properties of undefined (reading 'id')
2025-04-28 12:14:07 [ERROR]: Error in approving leave: Cannot read properties of undefined (reading 'id')
2025-04-28 12:14:51 [ERROR]: Error in approving leave: Cannot read properties of undefined (reading 'id')
2025-04-28 12:15:58 [ERROR]: Error in approving leave: Cannot read properties of undefined (reading 'id')
2025-04-28 12:16:35 [ERROR]: Error in rejecting leave: Cannot read properties of undefined (reading 'id')
2025-04-28 12:28:25 [ERROR]: Error applying for leave: date/time field value out of range: "2025-06-31"
2025-04-28 12:59:49 [ERROR]: Blockchain interaction failed, but leave was approved in database:
2025-04-28 12:59:49 [ERROR]: AggregateError
2025-04-28 13:15:14 [ERROR]: Error during leave approval process: execution reverted: "Employee does not exist" (action="estimateGas", data="0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000017456d706c6f79656520646f6573206e6f74206578697374000000000000000000", reason="Employee does not exist", transaction={ "data": "0x30f73abf0000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000000700000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000002465393139343030392d613561612d343234352d386534642d36663734306231393762663200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f46616d696c79207661636174696f6e0000000000000000000000000000000000", "from": "0xD5Ef4C18c389Da45967cb21365fe000a708e0Fa5", "to": "0xf7014aaaD8CE7ae5054c6391C71D593adC64855c" }, invocation=null, revert={ "args": [ "Employee does not exist" ], "name": "Error", "signature": "Error(string)" }, code=CALL_EXCEPTION, version=6.13.5)
{"level":"error","message":"Unable to connect to the database:","name":"SequelizeConnectionRefusedError","original":{"code":"ECONNREFUSED"},"parent":{"code":"ECONNREFUSED"},"service":"staffi-backend","stack":"SequelizeConnectionRefusedError\n    at Client._connectionCallback (C:\\Users\\uttam\\OneDrive\\Desktop\\Desktop Folders\\STAFFI\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:133:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\uttam\\OneDrive\\Desktop\\Desktop Folders\\STAFFI\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorEvent (C:\\Users\\uttam\\OneDrive\\Desktop\\Desktop Folders\\STAFFI\\backend\\node_modules\\pg\\lib\\client.js:346:19)\n    at Connection.emit (node:events:519:28)\n    at Socket.reportStreamError (C:\\Users\\uttam\\OneDrive\\Desktop\\Desktop Folders\\STAFFI\\backend\\node_modules\\pg\\lib\\connection.js:57:12)\n    at Socket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-04-28 13:57:35"}
{"level":"error","message":"Unable to connect to the database:","name":"SequelizeConnectionRefusedError","original":{"code":"ECONNREFUSED"},"parent":{"code":"ECONNREFUSED"},"service":"staffi-backend","stack":"SequelizeConnectionRefusedError\n    at Client._connectionCallback (C:\\Users\\uttam\\OneDrive\\Desktop\\Desktop Folders\\STAFFI\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:133:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\uttam\\OneDrive\\Desktop\\Desktop Folders\\STAFFI\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorEvent (C:\\Users\\uttam\\OneDrive\\Desktop\\Desktop Folders\\STAFFI\\backend\\node_modules\\pg\\lib\\client.js:346:19)\n    at Connection.emit (node:events:519:28)\n    at Socket.reportStreamError (C:\\Users\\uttam\\OneDrive\\Desktop\\Desktop Folders\\STAFFI\\backend\\node_modules\\pg\\lib\\connection.js:57:12)\n    at Socket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-04-28 13:59:37"}
{"level":"error","message":"Unable to connect to the database:","name":"SequelizeConnectionRefusedError","original":{"code":"ECONNREFUSED"},"parent":{"code":"ECONNREFUSED"},"service":"staffi-backend","stack":"SequelizeConnectionRefusedError\n    at Client._connectionCallback (C:\\Users\\uttam\\OneDrive\\Desktop\\Desktop Folders\\STAFFI\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:133:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\uttam\\OneDrive\\Desktop\\Desktop Folders\\STAFFI\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorEvent (C:\\Users\\uttam\\OneDrive\\Desktop\\Desktop Folders\\STAFFI\\backend\\node_modules\\pg\\lib\\client.js:346:19)\n    at Connection.emit (node:events:519:28)\n    at Socket.reportStreamError (C:\\Users\\uttam\\OneDrive\\Desktop\\Desktop Folders\\STAFFI\\backend\\node_modules\\pg\\lib\\connection.js:57:12)\n    at Socket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-04-28 13:59:46"}
